"""Seed des 42 metiers (migration depuis careers_database.dart).

Insere les 42 metiers (anciennement codes en dur cote app) dans la table
careers, desormais editables depuis le back-office et visibles par tous.
Idempotent : n'insere que si la table est vide (evite les doublons).

Revision ID: 017
Revises: 016
Create Date: 2026-06-06
"""
from alembic import op

revision = '017'
down_revision = '016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Idempotent : ne seed que si aucun metier n'existe encore.
    op.execute("""
DO $$
BEGIN
  IF (SELECT count(*) FROM careers) = 0 THEN
    INSERT INTO careers (
        id, name, description, sector_id, sector_name, image_url,
        required_skills, related_traits, education_path,
        salary_min_fcfa, salary_max_fcfa, salary_avg_fcfa, salary_note,
        job_demand, growth_trend, outlook_description, top_employers,
        entrepreneurship_potential, is_active
    ) VALUES
    (
        gen_random_uuid(),
        'Développeur Logiciel',
        'Le développeur logiciel conçoit, programme et maintient des applications informatiques. Au Togo, ce métier est en plein essor avec la digitalisation croissante des entreprises et l''émergence des startups tech.',
        (SELECT id FROM career_sectors WHERE name = 'Technologie & Informatique' LIMIT 1),
        'Technologie & Informatique',
        NULL,
        ARRAY['Programmation (Python, Java, JavaScript)', 'Résolution de problèmes', 'Travail en équipe', 'Apprentissage continu', 'Anglais technique']::text[],
        ARRAY['Investigateur', 'Conventionnel', 'Logico-Mathématique']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence en Informatique", "Licence en Génie Logiciel", "DUT Informatique", "Formation Bootcamp (6 mois intensif)"], "schools_in_togo": ["Université de Lomé - Faculté des Sciences", "ESIBA (École Supérieure d''Informatique)", "IAI-TOGO", "ESGIS"], "duration_years": 3, "certifications": "AWS, Google Cloud, Microsoft Azure"}'::jsonb,
        150000,
        800000,
        350000,
        'Les seniors (5+ ans) peuvent atteindre 1M+ FCFA, surtout en freelance pour des clients internationaux.',
        'high',
        'growing',
        'Secteur en forte croissance avec la transformation digitale. Opportunités locales et internationales (télétravail).',
        ARRAY['TOGOCOM', 'Moov Africa', 'Gozem', 'Semoa', 'Startups locales']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Analyste de Données',
        'L''analyste de données collecte, traite et interprète des données pour aider les entreprises à prendre des décisions éclairées. Métier émergent au Togo avec un fort potentiel.',
        (SELECT id FROM career_sectors WHERE name = 'Technologie & Informatique' LIMIT 1),
        'Technologie & Informatique',
        NULL,
        ARRAY['Statistiques et mathématiques', 'Excel avancé, SQL', 'Python ou R', 'Visualisation (Power BI, Tableau)', 'Esprit analytique']::text[],
        ARRAY['Investigateur', 'Conventionnel', 'Logico-Mathématique']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence en Statistiques", "Licence en Mathématiques Appliquées", "Master en Data Science", "Certifications en ligne (Coursera, DataCamp)"], "schools_in_togo": ["ENSEA (École Nationale de Statistique)", "Université de Lomé - Maths/Stats", "Formations en ligne certifiantes"], "duration_years": 3, "certifications": "Google Data Analytics, IBM Data Science"}'::jsonb,
        200000,
        700000,
        400000,
        'Forte demande internationale, possibilité de télétravail avec salaires alignés sur les marchés européens.',
        'high',
        'growing',
        'La data devient centrale pour toutes les organisations. Métier d''avenir avec peu de concurrence locale.',
        ARRAY['Banques (Ecobank, ORABANK)', 'Télécoms', 'ONG internationales', 'Consulting']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Médecin Généraliste',
        'Le médecin généraliste diagnostique et traite les maladies courantes, oriente vers les spécialistes et assure le suivi médical des patients. Profession très respectée au Togo avec un rôle social important.',
        '850c57d9-4fea-4caa-ae06-96ff27a28462'::uuid,
        'Sante',
        NULL,
        ARRAY['Connaissances médicales approfondies', 'Empathie et écoute', 'Résistance au stress', 'Communication', 'Éthique professionnelle']::text[],
        ARRAY['Social', 'Investigateur', 'Interpersonnelle']::text[],
        '{"minimum_level": "BAC+7", "recommended_formations": ["Doctorat en Médecine", "Spécialisation optionnelle (+3-5 ans)"], "schools_in_togo": ["Faculté des Sciences de la Santé - Université de Lomé", "Possibilité d''études au Maroc, Sénégal (bourses)"], "duration_years": 7, "certifications": "Inscription à l''Ordre des Médecins du Togo"}'::jsonb,
        300000,
        1500000,
        600000,
        'Revenus variables selon le secteur (public/privé) et la spécialisation. Les cliniques privées paient mieux.',
        'high',
        'stable',
        'Besoin permanent de médecins, surtout en zones rurales. Ratio médecin/population encore faible au Togo.',
        ARRAY['CHU Sylvanus Olympio', 'CHR Lomé Commune', 'Cliniques privées', 'ONG médicales (MSF, etc.)']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Infirmier(e)',
        'L''infirmier assure les soins aux patients, administre les traitements, et accompagne les malades au quotidien. Pilier essentiel du système de santé togolais.',
        '850c57d9-4fea-4caa-ae06-96ff27a28462'::uuid,
        'Sante',
        NULL,
        ARRAY['Soins infirmiers', 'Empathie', 'Rigueur', 'Travail en équipe', 'Gestion du stress']::text[],
        ARRAY['Social', 'Conventionnel', 'Interpersonnelle']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Diplôme d''État d''Infirmier", "Licence en Sciences Infirmières"], "schools_in_togo": ["École Nationale des Auxiliaires Médicaux (ENAM)", "ESTBA - Université de Lomé"], "duration_years": 3, "certifications": "Inscription à l''Ordre des Infirmiers"}'::jsonb,
        120000,
        400000,
        200000,
        'Salaires plus élevés dans le privé et les ONG internationales. Possibilité de travail à l''étranger.',
        'high',
        'growing',
        'Forte demande nationale et internationale. Métier stable avec sécurité d''emploi.',
        ARRAY['Hôpitaux publics', 'Cliniques privées', 'ONG médicales', 'Entreprises (infirmerie)']::text[],
        FALSE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Pharmacien',
        'Le pharmacien délivre les médicaments, conseille les patients et gère l''approvisionnement pharmaceutique. Profession réglementée et respectée.',
        '850c57d9-4fea-4caa-ae06-96ff27a28462'::uuid,
        'Sante',
        NULL,
        ARRAY['Connaissances pharmaceutiques', 'Précision et rigueur', 'Conseil aux patients', 'Gestion de stock', 'Réglementation']::text[],
        ARRAY['Investigateur', 'Conventionnel', 'Social']::text[],
        '{"minimum_level": "BAC+6", "recommended_formations": ["Doctorat en Pharmacie"], "schools_in_togo": ["Faculté des Sciences de la Santé - Université de Lomé", "Universités partenaires au Sénégal, Maroc"], "duration_years": 6, "certifications": "Inscription à l''Ordre des Pharmaciens du Togo"}'::jsonb,
        300000,
        1000000,
        500000,
        'Les propriétaires de pharmacies peuvent gagner beaucoup plus. L''industrie pharmaceutique offre aussi des opportunités.',
        'medium',
        'stable',
        'Nombre de pharmaciens réglementé. Marché stable avec bonnes opportunités pour les pharmacies en zone rurale.',
        ARRAY['Pharmacies officinales', 'Hôpitaux', 'Industrie pharmaceutique', 'Grossistes (SOTOMED, etc.)']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Enseignant',
        'L''enseignant transmet des connaissances et forme les futures générations. Métier noble et crucial pour le développement du Togo. Options variées: primaire, secondaire, supérieur.',
        '7abc0149-ab91-46fd-9999-a1c9b0cab266'::uuid,
        'Education',
        NULL,
        ARRAY['Maîtrise de la matière', 'Pédagogie', 'Patience', 'Communication', 'Gestion de classe']::text[],
        ARRAY['Social', 'Artistique', 'Linguistique']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["CAPES (Certificat d''Aptitude au Professorat)", "Licence dans la discipline + formation pédagogique", "ENS (École Normale Supérieure)"], "schools_in_togo": ["ENS Atakpamé", "Université de Lomé", "ENI (Enseignement Primaire)"], "duration_years": 3, "certifications": "CAPES, CAEN selon le niveau"}'::jsonb,
        100000,
        350000,
        180000,
        'Salaires dans le public selon l''échelon. Écoles privées internationales paient mieux (300K+).',
        'high',
        'stable',
        'Besoin constant d''enseignants qualifiés. Les matières scientifiques et l''anglais sont très demandés.',
        ARRAY['Éducation Nationale', 'Écoles privées', 'Établissements internationaux', 'Cours particuliers']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Comptable',
        'Le comptable gère les comptes, établit les bilans et assure la conformité financière des entreprises. Profession essentielle pour toute organisation.',
        '46110ad9-0763-44d9-900b-69c77b1fcd05'::uuid,
        'Finance & Banque',
        NULL,
        ARRAY['Comptabilité générale et analytique', 'Maîtrise des logiciels comptables', 'Fiscalité', 'Rigueur et précision', 'Organisation']::text[],
        ARRAY['Conventionnel', 'Investigateur', 'Logico-Mathématique']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["BTS Comptabilité", "Licence en Comptabilité", "DCG (Diplôme de Comptabilité et Gestion)", "DSCG, Expert-Comptable"], "schools_in_togo": ["ESAG-NDE", "UCAO", "Université de Lomé - FASEG", "ESGIS"], "duration_years": 2, "certifications": "Inscription OECT pour Expert-Comptable"}'::jsonb,
        120000,
        600000,
        250000,
        'Les experts-comptables et directeurs financiers peuvent dépasser 800K FCFA. Cabinet propre très lucratif.',
        'high',
        'stable',
        'Toute entreprise a besoin d''un comptable. Demande stable et opportunités d''évolution.',
        ARRAY['Cabinets comptables', 'Banques', 'Entreprises diverses', 'ONG']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Agent Bancaire',
        'L''agent bancaire gère les opérations bancaires, conseille les clients sur les produits financiers et participe au développement commercial de la banque.',
        '46110ad9-0763-44d9-900b-69c77b1fcd05'::uuid,
        'Finance & Banque',
        NULL,
        ARRAY['Connaissances bancaires', 'Relation client', 'Commercial', 'Analyse financière', 'Discrétion']::text[],
        ARRAY['Entrepreneur', 'Conventionnel', 'Social']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence en Banque-Finance", "Master en Finance", "BTS Banque"], "schools_in_togo": ["FASEG - Université de Lomé", "ESAG-NDE", "UCAO", "ESGIS"], "duration_years": 3, "certifications": "Certifications bancaires internes"}'::jsonb,
        200000,
        800000,
        350000,
        'Primes et avantages importants dans les grandes banques. Les directeurs d''agence dépassent 1M FCFA.',
        'medium',
        'stable',
        'Secteur bancaire mature mais en évolution digitale. Nouvelles compétences tech recherchées.',
        ARRAY['Ecobank', 'ORABANK', 'BTCI', 'UTB', 'Coris Bank']::text[],
        FALSE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Commercial / Chef des Ventes',
        'Le commercial développe le portefeuille clients, négocie les contrats et atteint les objectifs de vente. Rôle clé pour la croissance des entreprises.',
        '3a2a5f18-d1f7-4f12-a74d-e09ca0924b9e'::uuid,
        'Commerce & Entrepreneuriat',
        NULL,
        ARRAY['Négociation', 'Persuasion', 'Relation client', 'Atteinte d''objectifs', 'Résistance au stress']::text[],
        ARRAY['Entrepreneur', 'Social', 'Interpersonnelle']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["BTS Commerce", "Licence Marketing", "Master Commerce International"], "schools_in_togo": ["ESAG-NDE", "ESGIS", "UCAO", "Université de Lomé"], "duration_years": 2, "certifications": "Formations commerciales certifiantes"}'::jsonb,
        100000,
        700000,
        250000,
        'Commissions et primes peuvent doubler le salaire fixe. Les top performers gagnent très bien.',
        'high',
        'growing',
        'Toujours besoin de bons commerciaux. Secteurs FMCG, télécom et tech très actifs.',
        ARRAY['Nestlé', 'Unilever', 'Télécoms', 'Banques', 'Distribution']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Entrepreneur / Chef d''Entreprise',
        'L''entrepreneur crée et développe sa propre entreprise. Au Togo, l''écosystème entrepreneurial se développe avec de nombreuses opportunités dans le digital, l''agribusiness et les services.',
        '3a2a5f18-d1f7-4f12-a74d-e09ca0924b9e'::uuid,
        'Commerce & Entrepreneuriat',
        NULL,
        ARRAY['Vision stratégique', 'Leadership', 'Gestion financière', 'Résilience', 'Networking']::text[],
        ARRAY['Entrepreneur', 'Artistique', 'Intrapersonnelle']::text[],
        '{"minimum_level": "Variable", "recommended_formations": ["Tout diplôme pertinent au secteur", "Formations en entrepreneuriat", "MBA (optionnel)"], "schools_in_togo": ["Incubateurs: Woelab, CUBE", "FAIEJ", "Formations GIZ, AFD"], "duration_years": 0, "certifications": "Pas obligatoire, formations en gestion recommandées"}'::jsonb,
        0,
        5000000,
        300000,
        'Revenus très variables. Premiers mois/années difficiles. Potentiel de gains illimité avec le succès.',
        'high',
        'growing',
        'Le Togo encourage l''entrepreneuriat (FAIEJ, fonds). Opportunités dans le digital, l''agro et les services.',
        ARRAY['Votre propre entreprise']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Ingénieur Civil / BTP',
        'L''ingénieur civil conçoit et supervise la construction d''infrastructures: routes, bâtiments, ponts. Secteur en croissance avec les projets de développement au Togo.',
        'caf791a9-f3cf-4935-8999-351f41da266c'::uuid,
        'Ingenierie & Construction',
        NULL,
        ARRAY['Calcul de structures', 'Logiciels CAO (AutoCAD, etc.)', 'Gestion de chantier', 'Connaissances matériaux', 'Travail en équipe']::text[],
        ARRAY['Réaliste', 'Investigateur', 'Spatiale']::text[],
        '{"minimum_level": "BAC+5", "recommended_formations": ["Diplôme d''Ingénieur Génie Civil", "Master en BTP"], "schools_in_togo": ["ENSI - Université de Lomé", "FORMATEC", "Écoles d''ingénieurs au Maroc, Sénégal"], "duration_years": 5, "certifications": "Inscription Ordre des Ingénieurs"}'::jsonb,
        250000,
        1200000,
        500000,
        'Les chefs de projet et directeurs techniques dépassent 1M FCFA. Expatriation lucrative.',
        'high',
        'growing',
        'Nombreux projets d''infrastructure au Togo. Demande forte pour ingénieurs qualifiés.',
        ARRAY['Entreprises BTP locales', 'Groupes internationaux', 'Administration (Ministère)', 'Bureaux d''études']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Architecte',
        'L''architecte conçoit des bâtiments en alliant esthétique, fonctionnalité et normes techniques. Métier créatif très demandé dans un Togo en construction.',
        'caf791a9-f3cf-4935-8999-351f41da266c'::uuid,
        'Ingenierie & Construction',
        NULL,
        ARRAY['Conception architecturale', 'Logiciels 3D (Revit, SketchUp)', 'Créativité', 'Connaissance des normes', 'Relation client']::text[],
        ARRAY['Artistique', 'Réaliste', 'Spatiale']::text[],
        '{"minimum_level": "BAC+5", "recommended_formations": ["Diplôme d''Architecte"], "schools_in_togo": ["EAMAU (École Africaine) - Lomé", "Écoles d''architecture au Maroc, Bénin"], "duration_years": 5, "certifications": "Inscription Ordre des Architectes"}'::jsonb,
        200000,
        1000000,
        450000,
        'Les architectes avec leur propre cabinet et des projets prestigieux gagnent bien plus.',
        'medium',
        'growing',
        'Croissance urbaine = besoin d''architectes. Marchés publics et privés en développement.',
        ARRAY['Cabinets d''architecture', 'Entreprises BTP', 'Ministère de l''Urbanisme', 'Freelance']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Ingénieur Agronome',
        'L''agronome améliore les techniques agricoles, conseille les agriculteurs et développe des solutions pour augmenter les rendements. Secteur clé au Togo, pays à vocation agricole.',
        'c3a0d296-88ed-43ee-834b-1d28a05b608d'::uuid,
        'Agriculture & Environnement',
        NULL,
        ARRAY['Sciences agronomiques', 'Connaissance des cultures locales', 'Conseil agricole', 'Gestion de projet', 'Travail terrain']::text[],
        ARRAY['Réaliste', 'Investigateur', 'Naturaliste']::text[],
        '{"minimum_level": "BAC+5", "recommended_formations": ["Diplôme d''Ingénieur Agronome", "Master en Agronomie"], "schools_in_togo": ["ESA - Université de Lomé", "INFA de Tové", "Écoles au Bénin, Sénégal, Maroc"], "duration_years": 5, "certifications": "Certifications en agriculture durable"}'::jsonb,
        150000,
        700000,
        350000,
        'ONG et organisations internationales paient bien. L''agribusiness propre peut être très lucratif.',
        'high',
        'growing',
        'Agriculture = 40% du PIB togolais. Fort potentiel dans l''agribusiness et l''agriculture durable.',
        ARRAY['Ministère de l''Agriculture', 'ONG (GIZ, PNUD)', 'Entreprises agro-alimentaires', 'Agribusiness privé']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Développeur Mobile',
        'Le développeur mobile crée des applications Android et iOS. Métier en forte demande avec la pénétration croissante des smartphones en Afrique.',
        (SELECT id FROM career_sectors WHERE name = 'Technologie & Informatique' LIMIT 1),
        'Technologie & Informatique',
        NULL,
        ARRAY['Flutter, React Native ou Kotlin/Swift', 'Conception UI/UX mobile', 'APIs REST', 'Débogage mobile', 'Publication sur stores']::text[],
        ARRAY['Investigateur', 'Artistique', 'Conventionnel']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["Licence en Informatique", "BTS Informatique", "Bootcamp Mobile (3-6 mois)"], "schools_in_togo": ["IAI-TOGO", "ESIBA", "ESGIS", "Formations en ligne (Udemy, Coursera)"], "duration_years": 2, "certifications": "Google Associate Android Developer"}'::jsonb,
        150000,
        700000,
        320000,
        'Freelance international très lucratif. Upwork et Fiverr ouvrent des marchés globaux.',
        'high',
        'growing',
        'L''économie mobile africaine explose. Fintech, e-commerce, m-santé.',
        ARRAY['Gozem', 'Semoa', 'Startups Fintech', 'Freelance']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Administrateur Systèmes & Réseaux',
        'L''administrateur gère les serveurs, réseaux et sécurité informatique des entreprises. Métier stable et indispensable à toute organisation moderne.',
        (SELECT id FROM career_sectors WHERE name = 'Technologie & Informatique' LIMIT 1),
        'Technologie & Informatique',
        NULL,
        ARRAY['Linux / Windows Server', 'Réseaux (TCP/IP, VPN)', 'Sécurité informatique', 'Virtualisation (VMware, Hyper-V)', 'Cloud (AWS, Azure)']::text[],
        ARRAY['Investigateur', 'Conventionnel', 'Réaliste']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["BTS Réseaux & Télécoms", "Licence Génie Informatique", "Certifications Cisco (CCNA)"], "schools_in_togo": ["IAI-TOGO", "ESIBA", "Université de Lomé - IUT"], "duration_years": 2, "certifications": "CCNA, CompTIA Network+, Microsoft Azure"}'::jsonb,
        150000,
        600000,
        280000,
        'Les certifications internationales doublent la valeur sur le marché.',
        'high',
        'growing',
        'Toute entreprise, banque, ONG a besoin d''un admin réseau.',
        ARRAY['Banques', 'Télécoms', 'ONG', 'Administrations', 'BCEAO']::text[],
        FALSE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Responsable Digital / Chef de Projet IT',
        'Le chef de projet IT coordonne les équipes techniques, gère les délais et traduit les besoins métier en solutions informatiques.',
        (SELECT id FROM career_sectors WHERE name = 'Technologie & Informatique' LIMIT 1),
        'Technologie & Informatique',
        NULL,
        ARRAY['Gestion de projet (Agile, Scrum)', 'Communication transversale', 'Culture technique (sans coder)', 'Budget et planning', 'Outils collaboratifs']::text[],
        ARRAY['Entrepreneur', 'Conventionnel', 'Investigateur']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence en Informatique de Gestion", "Master Management des SI", "MBA avec spécialisation IT"], "schools_in_togo": ["ESGIS", "ESAG-NDE", "Université de Lomé"], "duration_years": 3, "certifications": "PMP, PRINCE2, Scrum Master"}'::jsonb,
        250000,
        900000,
        450000,
        'Profil hybride tech+business très recherché. Évolution vers DSI.',
        'high',
        'growing',
        'La transformation digitale crée une forte demande pour les chefs de projet IT.',
        ARRAY['Banques', 'Grandes entreprises', 'Consulting', 'ONG internationales']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Sage-Femme / Maïeuticien',
        'La sage-femme accompagne les femmes pendant la grossesse, l''accouchement et le post-partum. Profession indispensable pour améliorer la santé maternelle au Togo.',
        '850c57d9-4fea-4caa-ae06-96ff27a28462'::uuid,
        'Sante',
        NULL,
        ARRAY['Obstétrique et gynécologie', 'Soins néonataux', 'Empathie et gestion du stress', 'Protocoles d''urgence', 'Santé publique']::text[],
        ARRAY['Social', 'Conventionnel', 'Réaliste']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Diplôme d''État de Sage-Femme", "Licence en Maïeutique"], "schools_in_togo": ["ENAM (École Nationale des Auxiliaires Médicaux)", "ESTBA - Université de Lomé"], "duration_years": 3, "certifications": "Inscription à l''Ordre des Sages-Femmes"}'::jsonb,
        120000,
        450000,
        220000,
        'ONG de santé maternelle et cliniques privées offrent des salaires plus élevés.',
        'high',
        'growing',
        'Fort besoin national. Le taux de mortalité maternelle crée une urgence professionnelle.',
        ARRAY['Maternités publiques', 'Cliniques privées', 'ONG (UNFPA, UNICEF)', 'MSF']::text[],
        FALSE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Technicien de Laboratoire Médical',
        'Le laborantin réalise les analyses biologiques (sang, urines, microbiologie) qui guident le diagnostic médical. Métier discret mais essentiel.',
        '850c57d9-4fea-4caa-ae06-96ff27a28462'::uuid,
        'Sante',
        NULL,
        ARRAY['Analyses biologiques', 'Manipulation des réactifs', 'Rigueur et précision', 'Protocoles d''hygiène et sécurité', 'Informatique médicale']::text[],
        ARRAY['Investigateur', 'Conventionnel', 'Réaliste']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["BTS Analyses de Biologie Médicale", "Licence Sciences Biologiques"], "schools_in_togo": ["ENAM", "Faculté des Sciences - Université de Lomé"], "duration_years": 2, "certifications": "Accréditation ISO 15189 (normes labo)"}'::jsonb,
        100000,
        350000,
        190000,
        'Les laboratoires privés et les cliniques internationales paient mieux.',
        'high',
        'stable',
        'Demande constante dans les hôpitaux, cliniques, et laboratoires indépendants.',
        ARRAY['Hôpitaux publics', 'Cliniques privées', 'Laboratoires indépendants', 'ONG']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Formateur Professionnel',
        'Le formateur conçoit et anime des formations pour adultes en entreprise ou en centre de formation. Rôle clé dans le développement des compétences.',
        '7abc0149-ab91-46fd-9999-a1c9b0cab266'::uuid,
        'Education',
        NULL,
        ARRAY['Ingénierie pédagogique', 'Animation de groupe', 'Expertise métier', 'Communication orale', 'Évaluation des acquis']::text[],
        ARRAY['Social', 'Entrepreneur', 'Artistique']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence en Sciences de l''Éducation", "Licence dans la discipline + formation pédagogique", "Master en Ingénierie de Formation"], "schools_in_togo": ["ENS Atakpamé", "FASEG - Université de Lomé", "UCAO"], "duration_years": 3, "certifications": "Certification de formateur (CQP)"}'::jsonb,
        120000,
        500000,
        250000,
        'Les formateurs freelance pour ONG et entreprises gagnent bien. Journées facturées.',
        'high',
        'growing',
        'La formation professionnelle est prioritaire pour les entreprises et ONG au Togo.',
        ARRAY['Centres de formation', 'ONG (GIZ, AFD)', 'Entreprises (formation interne)', 'Freelance']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Conseiller d''Orientation Scolaire',
        'Le conseiller aide les élèves à construire leur projet scolaire et professionnel. Métier utile et valorisant au cœur de l''éducation nationale.',
        '7abc0149-ab91-46fd-9999-a1c9b0cab266'::uuid,
        'Education',
        NULL,
        ARRAY['Psychologie de l''adolescent', 'Connaissance du système éducatif', 'Entretien individuel', 'Tests d''orientation', 'Écoute et empathie']::text[],
        ARRAY['Social', 'Investigateur', 'Conventionnel']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence en Psychologie", "Licence en Sciences de l''Éducation", "Master en Conseil et Orientation"], "schools_in_togo": ["ENS Atakpamé", "Université de Lomé - Psychologie"], "duration_years": 3, "certifications": "CAPES Orientation, formations spécialisées"}'::jsonb,
        100000,
        300000,
        180000,
        'Fonction publique avec évolution par échelon. Privé et ONG offrent plus.',
        'medium',
        'growing',
        'Les établissements privés et les plateformes numériques créent de nouveaux débouchés.',
        ARRAY['Éducation Nationale', 'Lycées privés', 'Plateformes EdTech', 'ONG jeunesse']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Responsable Pédagogique / Directeur d''École',
        'Le responsable pédagogique coordonne les programmes, encadre les enseignants et veille à la qualité de l''enseignement.',
        '7abc0149-ab91-46fd-9999-a1c9b0cab266'::uuid,
        'Education',
        NULL,
        ARRAY['Leadership éducatif', 'Gestion d''équipe', 'Élaboration de curricula', 'Suivi des résultats', 'Relation parents/partenaires']::text[],
        ARRAY['Social', 'Entrepreneur', 'Conventionnel']::text[],
        '{"minimum_level": "BAC+5", "recommended_formations": ["Master en Administration Éducative", "Master en Sciences de l''Éducation", "Diplôme d''administration scolaire"], "schools_in_togo": ["ENS Atakpamé", "Université de Lomé", "UCAO"], "duration_years": 5, "certifications": "Autorisation d''ouverture d''établissement (MEN Togo)"}'::jsonb,
        200000,
        800000,
        380000,
        'Les directeurs d''écoles privées réputées ont des revenus attractifs.',
        'medium',
        'stable',
        'Multiplication des établissements privés = besoin de cadres pédagogiques.',
        ARRAY['Groupes scolaires privés', 'Écoles internationales', 'ONG éducation', 'MEN Togo']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Analyste Financier',
        'L''analyste financier évalue la santé financière des entreprises, analyse les marchés et formule des recommandations d''investissement.',
        '46110ad9-0763-44d9-900b-69c77b1fcd05'::uuid,
        'Finance & Banque',
        NULL,
        ARRAY['Analyse financière et comptable', 'Modélisation financière (Excel avancé)', 'Marchés financiers', 'Rédaction de rapports', 'Anglais professionnel']::text[],
        ARRAY['Conventionnel', 'Investigateur', 'Entrepreneur']::text[],
        '{"minimum_level": "BAC+4", "recommended_formations": ["Master Finance d''Entreprise", "Master Banque & Finance", "Licence + CFA (Chartered Financial Analyst)"], "schools_in_togo": ["FASEG - Université de Lomé", "ESAG-NDE", "ESGIS"], "duration_years": 4, "certifications": "CFA, ACCA, certifications Bloomberg"}'::jsonb,
        300000,
        1200000,
        550000,
        'Profil très demandé par les banques, fonds d''investissement et cabinets de conseil.',
        'medium',
        'growing',
        'Le développement des marchés financiers régionaux BRVM crée des opportunités.',
        ARRAY['Ecobank', 'ORABANK', 'Fonds d''investissement', 'Cabinets conseil', 'BCEAO']::text[],
        FALSE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Agent / Chargé d''Assurance',
        'L''agent d''assurance conseille les clients sur les produits (vie, auto, habitation, santé), gère les sinistres et développe son portefeuille.',
        '46110ad9-0763-44d9-900b-69c77b1fcd05'::uuid,
        'Finance & Banque',
        NULL,
        ARRAY['Techniques d''assurance', 'Commercial et négociation', 'Gestion des sinistres', 'Analyse des risques', 'Relation client']::text[],
        ARRAY['Entrepreneur', 'Conventionnel', 'Social']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["BTS Assurance", "Licence Banque-Assurance", "Formations internes (FANAF)"], "schools_in_togo": ["ESAG-NDE", "UCAO", "Université de Lomé"], "duration_years": 2, "certifications": "Certifications FANAF (Fédération Africaine des Assureurs)"}'::jsonb,
        100000,
        600000,
        220000,
        'Les commissions sur ventes peuvent dépasser le salaire de base. Potentiel élevé.',
        'medium',
        'growing',
        'Le taux de pénétration de l''assurance au Togo est faible = fort potentiel de développement.',
        ARRAY['NSIA Assurances', 'Gras Savoye', 'GFA Vie', 'COLINA', 'Compagnies locales']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Contrôleur de Gestion',
        'Le contrôleur de gestion suit les performances financières de l''entreprise, pilote les budgets et aide à la prise de décision stratégique.',
        '46110ad9-0763-44d9-900b-69c77b1fcd05'::uuid,
        'Finance & Banque',
        NULL,
        ARRAY['Comptabilité analytique', 'Tableaux de bord et reporting', 'Analyse des écarts budgétaires', 'Excel / Power BI', 'Planification financière']::text[],
        ARRAY['Conventionnel', 'Investigateur', 'Entrepreneur']::text[],
        '{"minimum_level": "BAC+4", "recommended_formations": ["Master Contrôle de Gestion", "Master Finance & Comptabilité", "DSCG (Diplôme Supérieur de Comptabilité)"], "schools_in_togo": ["FASEG - Université de Lomé", "ESAG-NDE", "ESGIS"], "duration_years": 4, "certifications": "DSCG, certifications OHADA"}'::jsonb,
        280000,
        1000000,
        500000,
        'Poste stratégique avec forte évolution vers DAF (Directeur Administratif et Financier).',
        'high',
        'stable',
        'Indispensable dans les grandes entreprises, multinationales et ONG.',
        ARRAY['Multinationales', 'Banques', 'Grandes entreprises togolaises', 'ONG internationales']::text[],
        FALSE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Responsable Marketing / Digital',
        'Le responsable marketing conçoit et pilote les stratégies de communication, gère les réseaux sociaux, les campagnes et l''image de marque.',
        '3a2a5f18-d1f7-4f12-a74d-e09ca0924b9e'::uuid,
        'Commerce & Entrepreneuriat',
        NULL,
        ARRAY['Stratégie marketing', 'Réseaux sociaux et publicité digitale', 'Rédaction et création de contenu', 'Analyse des données (Google Analytics)', 'Créativité']::text[],
        ARRAY['Entrepreneur', 'Artistique', 'Social']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence Marketing", "Master en Communication et Marketing", "BTS Commerce + formations digitales"], "schools_in_togo": ["ESAG-NDE", "ESGIS", "UCAO", "Formations en ligne (Google, HubSpot)"], "duration_years": 3, "certifications": "Google Ads, Meta Blueprint, HubSpot Marketing"}'::jsonb,
        120000,
        700000,
        300000,
        'Le marketing digital freelance pour clients africains et internationaux est très rentable.',
        'high',
        'growing',
        'Toutes les entreprises ont besoin de visibilité digitale. Marché en explosion.',
        ARRAY['Agences digitales', 'Startups', 'Grandes entreprises', 'Freelance']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Logisticien / Gestionnaire Import-Export',
        'Le logisticien gère la chaîne d''approvisionnement, les flux de marchandises, les douanes et les transports. Rôle clé dans le commerce togolais.',
        '3a2a5f18-d1f7-4f12-a74d-e09ca0924b9e'::uuid,
        'Commerce & Entrepreneuriat',
        NULL,
        ARRAY['Gestion de la supply chain', 'Réglementation douanière', 'Incoterms et commerce international', 'Logiciels de gestion (ERP)', 'Négociation fournisseurs']::text[],
        ARRAY['Conventionnel', 'Entrepreneur', 'Réaliste']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["BTS Commerce International", "Licence Logistique & Transport", "Master Supply Chain Management"], "schools_in_togo": ["Université de Lomé - FASEG", "ESAG-NDE", "Écoles de transit et douane"], "duration_years": 2, "certifications": "Déclarant en douane, CSCMP"}'::jsonb,
        150000,
        700000,
        300000,
        'Le port autonome de Lomé et le transit font de la logistique un secteur clé au Togo.',
        'high',
        'growing',
        'Port de Lomé = hub régional. Forte demande en logistique et transit.',
        ARRAY['TOGO PORT', 'Transitaires', 'Groupes GETMA, BOLLORÉ', 'Entreprises import-export']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Ingénieur Électricien / Électrotechnicien',
        'L''ingénieur électricien conçoit et maintient les installations électriques industrielles, les réseaux d''énergie et les systèmes d''automatisation.',
        'caf791a9-f3cf-4935-8999-351f41da266c'::uuid,
        'Ingenierie & Construction',
        NULL,
        ARRAY['Électrotechnique et électronique de puissance', 'Normes électriques', 'Automatisation (PLC)', 'Énergie solaire et renouvelable', 'Sécurité électrique']::text[],
        ARRAY['Réaliste', 'Investigateur', 'Conventionnel']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence Génie Électrique", "DUT Génie Électrique et Informatique Industrielle", "Diplôme d''Ingénieur Électricien"], "schools_in_togo": ["ENSI - Université de Lomé", "IUT Lomé", "FORMATEC"], "duration_years": 3, "certifications": "Habilitation électrique, Certifications énergie solaire"}'::jsonb,
        200000,
        900000,
        400000,
        'Le boom du solaire et des énergies renouvelables crée des opportunités inédites.',
        'high',
        'growing',
        'CEET, énergies renouvelables et construction industrielle tirent la demande.',
        ARRAY['CEET', 'SINOPEC', 'Entreprises minières', 'Sociétés solaires', 'BTP industriel']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Technicien Topographe / Géomètre',
        'Le topographe mesure et cartographie les terrains, indispensable pour les projets de construction, d''urbanisme et de gestion foncière.',
        'caf791a9-f3cf-4935-8999-351f41da266c'::uuid,
        'Ingenierie & Construction',
        NULL,
        ARRAY['Levés topographiques (station totale, GPS)', 'SIG (ArcGIS, QGIS)', 'Dessin technique (AutoCAD)', 'Droit foncier', 'Travail terrain']::text[],
        ARRAY['Réaliste', 'Investigateur', 'Conventionnel']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["DUT Génie Civil option Topographie", "BTS Géomètre-Topographe", "Licence Génie Géomatique"], "schools_in_togo": ["IUT - Université de Lomé", "INFA de Tové (formation agricole/topographie)", "Écoles au Bénin et Ghana"], "duration_years": 2, "certifications": "Inscription à l''Ordre des Géomètres Experts"}'::jsonb,
        150000,
        600000,
        280000,
        'Les géomètres experts indépendants avec clientèle privée gagnent très bien.',
        'high',
        'growing',
        'Urbanisation rapide et projets fonciers = forte demande constante.',
        ARRAY['Ministère de l''Urbanisme', 'Bureaux d''études', 'Mairies', 'Entreprises BTP']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Technicien en Génie Mécanique / Maintenance',
        'Le technicien assure la maintenance préventive et corrective des équipements industriels, véhicules et machines de production.',
        'caf791a9-f3cf-4935-8999-351f41da266c'::uuid,
        'Ingenierie & Construction',
        NULL,
        ARRAY['Mécanique générale et industrielle', 'Lecture de plans techniques', 'Diagnostic et réparation', 'Hydraulique et pneumatique', 'Sécurité industrielle']::text[],
        ARRAY['Réaliste', 'Conventionnel', 'Investigateur']::text[],
        '{"minimum_level": "BAC", "recommended_formations": ["CAP Mécanique", "BTS Maintenance Industrielle", "Licence Génie Mécanique"], "schools_in_togo": ["CFPT (Centre de Formation Professionnelle et Technique)", "IUT - Université de Lomé", "Centres professionnels privés"], "duration_years": 2, "certifications": "Habilitations sécurité, certifications constructeurs"}'::jsonb,
        100000,
        500000,
        220000,
        'Industries, entreprises minières et BTP offrent les meilleurs salaires.',
        'high',
        'stable',
        'Industrie, transport et BTP ont besoin en permanence de techniciens qualifiés.',
        ARRAY['Ciments du Togo', 'Phosphates du Togo (OTP)', 'Garages industriels', 'BTP', 'CEET']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Vétérinaire',
        'Le vétérinaire soigne les animaux, assure la surveillance sanitaire et contribue à la sécurité alimentaire (bétail, volaille, aquaculture).',
        'c3a0d296-88ed-43ee-834b-1d28a05b608d'::uuid,
        'Agriculture & Environnement',
        NULL,
        ARRAY['Médecine vétérinaire', 'Chirurgie animale', 'Épidémiologie animale', 'Inspection vétérinaire', 'Santé publique vétérinaire']::text[],
        ARRAY['Social', 'Investigateur', 'Réaliste']::text[],
        '{"minimum_level": "BAC+5", "recommended_formations": ["Doctorat en Médecine Vétérinaire"], "schools_in_togo": ["École de Médecine Vétérinaire au Bénin (ENSTA)", "Universités au Maroc, Sénégal, Côte d''Ivoire"], "duration_years": 5, "certifications": "Inscription à l''Ordre des Vétérinaires du Togo"}'::jsonb,
        200000,
        800000,
        400000,
        'Clinique privée et travail international très rémunérateurs.',
        'high',
        'growing',
        'Élevage intensif et aquaculture en développement. Manque de vétérinaires qualifiés.',
        ARRAY['Ministère de l''Agriculture', 'FAO', 'Cliniques vétérinaires', 'Industries agro']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Ingénieur en Environnement / Développement Durable',
        'L''ingénieur en environnement évalue les impacts environnementaux, gère les ressources naturelles et accompagne la transition vers le développement durable.',
        'c3a0d296-88ed-43ee-834b-1d28a05b608d'::uuid,
        'Agriculture & Environnement',
        NULL,
        ARRAY['Évaluation d''impact environnemental', 'Gestion des ressources en eau et en sol', 'Réglementation environnementale', 'SIG et cartographie', 'Plaidoyer et sensibilisation']::text[],
        ARRAY['Investigateur', 'Réaliste', 'Social']::text[],
        '{"minimum_level": "BAC+5", "recommended_formations": ["Licence en Sciences de l''Environnement", "Master Environnement et Développement Durable", "Master Gestion des Ressources Naturelles"], "schools_in_togo": ["Université de Lomé - Sciences", "INFA de Tové", "Universités au Maroc (Mohamed VI)"], "duration_years": 5, "certifications": "Certifications ISO 14001, Lead Auditor Environnement"}'::jsonb,
        200000,
        900000,
        420000,
        'Les ONG internationales et bailleurs de fonds paient très bien.',
        'high',
        'growing',
        'Changement climatique et projets de développement = forte demande en experts environnement.',
        ARRAY['PNUD', 'PNUE', 'GIZ', 'Ministère de l''Environnement', 'Bureaux d''études']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Technicien Agroalimentaire',
        'Le technicien agroalimentaire contrôle la qualité des produits alimentaires, gère la transformation et veille au respect des normes sanitaires.',
        'c3a0d296-88ed-43ee-834b-1d28a05b608d'::uuid,
        'Agriculture & Environnement',
        NULL,
        ARRAY['Biochimie alimentaire', 'Contrôle qualité (HACCP)', 'Procédés de transformation', 'Microbiologie alimentaire', 'Gestion de production']::text[],
        ARRAY['Réaliste', 'Conventionnel', 'Investigateur']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["BTS Industries Agroalimentaires", "Licence en Sciences des Aliments", "Master Agroalimentaire et Nutrition"], "schools_in_togo": ["Université de Lomé - Sciences", "INFA de Tové", "ITRA (Institut Togolais de Recherche Agronomique)"], "duration_years": 2, "certifications": "HACCP, ISO 22000 (sécurité alimentaire)"}'::jsonb,
        120000,
        450000,
        240000,
        'L''agro-industrie locale et les exportations (café, cacao) offrent de bonnes perspectives.',
        'high',
        'growing',
        'Transformation locale des produits agricoles = priorité nationale. Secteur porteur.',
        ARRAY['NIOTO', 'Entreprises agro-industrielles', 'ONG (FAO)', 'ITRA', 'Supermarchés']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Designer Graphique',
        'Le designer graphique crée des visuels pour la communication: logos, affiches, interfaces web. Métier créatif en forte demande avec la digitalisation.',
        '58a6c91d-e6ee-47f2-a9b8-8edf05686cdf'::uuid,
        'Arts & Media',
        NULL,
        ARRAY['Créativité visuelle', 'Maîtrise Adobe (Photoshop, Illustrator)', 'Sens artistique', 'Tendances design', 'Communication client']::text[],
        ARRAY['Artistique', 'Entrepreneur', 'Spatiale']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["BTS Design Graphique", "Licence en Arts Graphiques", "Formations professionnelles (3-6 mois)"], "schools_in_togo": ["IBTC", "Formations privées diverses", "Apprentissage autodidacte + portfolio"], "duration_years": 2, "certifications": "Adobe Certified, expérience et portfolio clés"}'::jsonb,
        80000,
        450000,
        200000,
        'Le freelance pour clients internationaux peut rapporter bien plus. Portfolio = clé du succès.',
        'high',
        'growing',
        'Tout business a besoin de visuels. Forte demande locale et opportunités internationales en freelance.',
        ARRAY['Agences de communication', 'Entreprises diverses', 'Freelance', 'Startups']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Journaliste',
        'Le journaliste collecte, vérifie et diffuse l''information. Au Togo, les médias se diversifient avec le digital, créant de nouvelles opportunités.',
        '58a6c91d-e6ee-47f2-a9b8-8edf05686cdf'::uuid,
        'Arts & Media',
        NULL,
        ARRAY['Rédaction et style', 'Curiosité et investigation', 'Éthique journalistique', 'Outils multimédia', 'Réseaux sociaux']::text[],
        ARRAY['Artistique', 'Social', 'Linguistique']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence en Journalisme", "Licence en Communication", "Master Journalisme"], "schools_in_togo": ["ISICA", "Université de Lomé - Communication", "ESTACOM"], "duration_years": 3, "certifications": "Carte de presse"}'::jsonb,
        80000,
        400000,
        180000,
        'Les médias internationaux et correspondants étrangers sont mieux payés. Piges complémentaires possibles.',
        'medium',
        'stable',
        'Médias traditionnels en difficulté mais le digital ouvre de nouvelles voies (podcasts, YouTube).',
        ARRAY['Togovi TV', 'TVT', 'Médias en ligne', 'Correspondants presse étrangère']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Photographe / Vidéaste',
        'Le photographe-vidéaste capture des images et vidéos pour les événements, la publicité, les médias et les réseaux sociaux.',
        '58a6c91d-e6ee-47f2-a9b8-8edf05686cdf'::uuid,
        'Arts & Media',
        NULL,
        ARRAY['Maîtrise des équipements photo/vidéo', 'Montage vidéo (Premiere, Final Cut)', 'Retouche photo (Lightroom, Photoshop)', 'Sens artistique et de la composition', 'Marketing personnel']::text[],
        ARRAY['Artistique', 'Entrepreneur', 'Réaliste']::text[],
        '{"minimum_level": "BAC", "recommended_formations": ["Formations privées en photographie", "BTS Audiovisuel", "Apprentissage autodidacte + portfolio"], "schools_in_togo": ["Centres de formation privés à Lomé", "Apprentissage en studio", "Formations en ligne (YouTube, Skillshare)"], "duration_years": 1, "certifications": "Portfolio professionnel = meilleure carte de visite"}'::jsonb,
        80000,
        600000,
        200000,
        'Les événements (mariages, entreprises) et les clients internationaux en freelance rapportent bien.',
        'high',
        'growing',
        'La demande en contenu visuel pour réseaux sociaux, publicité et événements explose.',
        ARRAY['Médias', 'Agences de communication', 'Événementiel', 'Freelance']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Créateur de Contenu Digital / Community Manager',
        'Le créateur de contenu produit des posts, vidéos, podcasts et stories pour les marques et médias. Le community manager gère les communautés en ligne.',
        '58a6c91d-e6ee-47f2-a9b8-8edf05686cdf'::uuid,
        'Arts & Media',
        NULL,
        ARRAY['Rédaction web et copywriting', 'Réseaux sociaux (Instagram, TikTok, LinkedIn)', 'Production vidéo courte', 'Stratégie de contenu', 'Analyse des statistiques']::text[],
        ARRAY['Artistique', 'Social', 'Entrepreneur']::text[],
        '{"minimum_level": "BAC", "recommended_formations": ["BTS Communication", "Licence Marketing Digital", "Formations certifiantes en ligne (Meta, Google)"], "schools_in_togo": ["ISICA", "Formations privées de communication", "Apprentissage autodidacte"], "duration_years": 1, "certifications": "Meta Blueprint, Google Digital Garage"}'::jsonb,
        80000,
        500000,
        180000,
        'Les créateurs avec audience peuvent monétiser via sponsoring et formations.',
        'high',
        'growing',
        'Chaque entreprise a besoin de présence digitale. Marché en forte croissance.',
        ARRAY['Agences digitales', 'Startups', 'Médias', 'Freelance', 'Propre audience']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Designer UX/UI',
        'Le designer UX/UI conçoit des interfaces numériques intuitives et esthétiques pour les applications mobiles et sites web.',
        '58a6c91d-e6ee-47f2-a9b8-8edf05686cdf'::uuid,
        'Arts & Media',
        NULL,
        ARRAY['Figma, Sketch, Adobe XD', 'Principes d''ergonomie', 'Prototypage et wireframing', 'Recherche utilisateur', 'Collaboration avec développeurs']::text[],
        ARRAY['Artistique', 'Investigateur', 'Conventionnel']::text[],
        '{"minimum_level": "BAC+2", "recommended_formations": ["BTS Design Graphique + formations UX", "Bootcamp UX/UI (3-6 mois)", "Licence en Design Numérique"], "schools_in_togo": ["Formations en ligne (Google UX Design, Coursera)", "IBTC", "Apprentissage autodidacte + portfolio"], "duration_years": 2, "certifications": "Google UX Design Certificate"}'::jsonb,
        150000,
        700000,
        320000,
        'Freelance international très accessible depuis Lomé via plateformes comme Toptal.',
        'high',
        'growing',
        'Tout produit digital a besoin d''un UX designer. Marché en pleine croissance.',
        ARRAY['Startups Tech', 'Agences digitales', 'Gozem', 'Banques digitales', 'Freelance']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Avocat',
        'L''avocat défend et conseille ses clients en matière juridique. Profession prestigieuse nécessitant rigueur et éloquence.',
        'bdf88e26-d594-42e6-a265-fdf24c607f48'::uuid,
        'Droit & Administration',
        NULL,
        ARRAY['Droit et jurisprudence', 'Éloquence et argumentation', 'Analyse et synthèse', 'Éthique professionnelle', 'Négociation']::text[],
        ARRAY['Entrepreneur', 'Social', 'Linguistique']::text[],
        '{"minimum_level": "BAC+5", "recommended_formations": ["Maîtrise en Droit", "CAPA (Certificat d''Aptitude à la Profession d''Avocat)"], "schools_in_togo": ["Faculté de Droit - Université de Lomé", "Stage au Barreau de Lomé"], "duration_years": 5, "certifications": "Inscription au Barreau"}'::jsonb,
        200000,
        2000000,
        500000,
        'Les avocats d''affaires et cabinets internationaux gagnent beaucoup plus. Réputation = revenus.',
        'medium',
        'stable',
        'Besoin constant de juristes. Le droit des affaires et international sont porteurs.',
        ARRAY['Cabinets d''avocats', 'Entreprises (direction juridique)', 'Organisations internationales', 'Indépendant']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Responsable Ressources Humaines',
        'Le RH gère le recrutement, la formation, les carrières et les relations sociales. Fonction stratégique dans les organisations modernes.',
        'bdf88e26-d594-42e6-a265-fdf24c607f48'::uuid,
        'Droit & Administration',
        NULL,
        ARRAY['Gestion des talents', 'Droit du travail', 'Communication', 'Psychologie', 'Organisation']::text[],
        ARRAY['Social', 'Conventionnel', 'Interpersonnelle']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence en GRH", "Master RH", "Master en Psychologie du travail"], "schools_in_togo": ["FASEG - Université de Lomé", "ESAG-NDE", "UCAO"], "duration_years": 3, "certifications": "Certifications SHRM, formations continues"}'::jsonb,
        150000,
        700000,
        300000,
        'Les DRH de grandes entreprises et multinationales dépassent 1M FCFA avec avantages.',
        'medium',
        'growing',
        'La gestion des talents devient stratégique. Compétences en digital RH recherchées.',
        ARRAY['Grandes entreprises', 'Multinationales', 'ONG', 'Cabinets de recrutement']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Notaire',
        'Le notaire authentifie les actes juridiques (contrats, successions, ventes immobilières), conseille ses clients et sécurise leurs transactions.',
        'bdf88e26-d594-42e6-a265-fdf24c607f48'::uuid,
        'Droit & Administration',
        NULL,
        ARRAY['Droit civil et notarial', 'Gestion patrimoniale', 'Rigueur documentaire', 'Relation clientèle', 'Informatique juridique']::text[],
        ARRAY['Conventionnel', 'Social', 'Entrepreneur']::text[],
        '{"minimum_level": "BAC+6", "recommended_formations": ["Master en Droit Notarial", "Diplôme Supérieur de Notariat"], "schools_in_togo": ["Faculté de Droit - Université de Lomé", "Stage en étude notariale"], "duration_years": 6, "certifications": "Nomination par le Ministre de la Justice"}'::jsonb,
        400000,
        3000000,
        900000,
        'Les notaires avec leur propre étude ont des revenus très élevés et stables.',
        'medium',
        'stable',
        'Profession réglementée à nombre limité. Très bonnes perspectives pour ceux qui y accèdent.',
        ARRAY['Étude notariale', 'Tribunaux', 'Administrations foncières']::text[],
        TRUE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Administrateur Civil / Fonctionnaire',
        'L''administrateur civil gère les affaires publiques, met en œuvre les politiques gouvernementales et assure le service aux citoyens.',
        'bdf88e26-d594-42e6-a265-fdf24c607f48'::uuid,
        'Droit & Administration',
        NULL,
        ARRAY['Droit public et administratif', 'Gestion publique', 'Rédaction administrative', 'Coordination interministérielle', 'Éthique du service public']::text[],
        ARRAY['Conventionnel', 'Social', 'Entrepreneur']::text[],
        '{"minimum_level": "BAC+3", "recommended_formations": ["Licence en Droit", "Licence en Administration Publique", "ENAP (École Nationale d''Administration)"], "schools_in_togo": ["ENAM (École Nationale d''Administration et de Magistrature)", "Université de Lomé - Droit"], "duration_years": 3, "certifications": "Concours de la Fonction Publique"}'::jsonb,
        150000,
        600000,
        280000,
        'Sécurité d''emploi et avancement à l''ancienneté. Retraite garantie.',
        'medium',
        'stable',
        'L''administration publique reste un employeur majeur au Togo.',
        ARRAY['Ministères', 'Collectivités locales', 'Préfectures', 'Ambassades']::text[],
        FALSE,
        TRUE
    ),
    (
        gen_random_uuid(),
        'Juriste d''Entreprise / Conseiller Juridique',
        'Le juriste d''entreprise assure la conformité légale des opérations, rédige les contrats et protège les intérêts juridiques de l''organisation.',
        'bdf88e26-d594-42e6-a265-fdf24c607f48'::uuid,
        'Droit & Administration',
        NULL,
        ARRAY['Droit des affaires (OHADA)', 'Rédaction de contrats', 'Droit social et fiscal', 'Veille réglementaire', 'Négociation juridique']::text[],
        ARRAY['Conventionnel', 'Entrepreneur', 'Investigateur']::text[],
        '{"minimum_level": "BAC+4", "recommended_formations": ["Master Droit des Affaires", "Master Droit OHADA", "Master Juriste d''Entreprise"], "schools_in_togo": ["Faculté de Droit - Université de Lomé", "ESGIS (option juridique)"], "duration_years": 4, "certifications": "Certification OHADA, formations en droit des affaires"}'::jsonb,
        250000,
        1000000,
        480000,
        'Les juristes OHADA sont très recherchés dans toute l''Afrique de l''Ouest.',
        'high',
        'growing',
        'Développement des affaires en Afrique = besoin croissant en juristes spécialisés OHADA.',
        ARRAY['Multinationales', 'Banques', 'Cabinets juridiques', 'Organisations internationales']::text[],
        FALSE,
        TRUE
    )
    ;
  END IF;
END $$;
""")


def downgrade() -> None:
    # On ne supprime pas (donnees editoriales potentiellement modifiees en prod).
    pass
